services:
  - type: web
    name: celr-app
    env: docker
    repo: https://github.com/Robert170387/CELR_app.git
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        value: celr_app
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_CA
        sync: false
      - key: APP_KEY
        sync: false
      - key: SESSION_LIFETIME
        value: "3600"
      - key: SESSION_SECURE
        value: "true"
    healthCheckPath: /login.php
